model:
  model_name: "openai/whisper-medium"
  model_size: "medium"

data:
  eval_csv: "/ceph/dpandya/notsofar/nsfd_adap_segments/eval_segments.csv"

adapter:
  dir: "/ceph/dpandya/notsofar/nsfd_adap_segments/adapter_base/medium/"