model:
  model_name: "openai/whisper-large-v3"
  model_size: "large"

data:
  eval_csv: "/ceph/dpandya/notsofar/nsfd_adap_segments/eval_segments.csv"

adapter:
  dir: "/ceph/dpandya/notsofar/nsfd_adap_segments/adapter_base/large/"