model:
  model_name: 'openai/whisper-large-v3'
  model_size: 'large'

data:
  train_ds_dir: '/ceph/dpandya/notsofar/nsfd_adap_segments/train_set_features'
  adapter_base_dir: '/ceph/dpandya/notsofar/nsfd_adap_segments/adapter_base'